### ISSUE TITLE
List::Util missing 'uniq' on some common distros

### ISSUE THREAD

**Issue by roycewilliams** [0xbsec/duprule#29]
duprule appears to have a dependency on a newer version of List::Util than the one that ships with Ubuntu 16.04 LTS. I'm using the version of List::Util that ships with perl 5.22.1:

$ perl ./duprule.pl
"uniq" is not exported by the List::Util module
Can't continue after import errors at ./duprule.pl line 4.
BEGIN failed--compilation aborted at ./duprule.pl line 4.

For better backward compatibility, some options might be:

* switching to a standalone implementation of uniq

* requiring List::Util 1.44 and giving a warning

* using List::MoreUtils (which is in the Ubuntu repositories as liblist-moreutils-perl)

**Comment by mhasbini** [comment]
Closed by #30.
