### ISSUE TITLE
no line breaks

### ISSUE THREAD

**Issue by Shooter3k** [0xbsec/duprule#32]
I'm trying to run this in Windows 10 on dive.rule and the output doesn't have any line breaks. 

command: duprule < dive.rule        
example output: 

8*39^"o2ru '9 $9^3 ^8O9A K *6A*09s?"y3O31 sbU Eo9ai3l*34 Ky2]o1IO25 s8.D2 O31 EZ1o97c $1 ^1l ^x $x ^x $xc '9 $9^7 ^1 ^0$J]*16$8 $1 $8+2-6*8A,A O72 s#dO78 f^PoB-^ST8[^O-7s2eY2E OB2 *53^b ^f$8 $9 $9$d $1s_b[E O49^X}sS@D8+8*B9,8lc r*52 u O86s#tLB*65u '9 $8+9*9Asjy*B0 OA3 $.^4 ^3+A +C*76 O3A$5 $0 $5.3 O18 s)z^6 ^1 ^1^c ^CO73 t -B} y4$y $ei76 i73s|*$8i15O06 s#Yo34sN!O24 $ii74 i77i75 i76$! O49 i7V$_ $1iB-lsaH$p $a $tO96 o22O96 Y2c ^7 ^7}s)7'No8zY1*36Y2 O9Ar $4 $4i71s!1o5d*6A $A O93k O81 O48i6<^1*B3l $9 $2O73 *96sVLEo5v]ss6^r ^o ^f+A -8i32 i31i72 i76s/A '5 O5Bo0YO71 sx,+1z1Y1}l $9 $3fcsBzs(y}o9!o7uo68o7Z O65s>C+6K$m $a $piA>T3-3 o94$w $eE]Y1$5 $9 $5^C O81$k $e $yr*56*31lO34 sGT [+6i8ass_o63$e $6*61 +6 O25s01]$l $sO81 O3A} O69 OB3c $_ $1OA5 *75s29^8 ^0$i $c $e} O95oA2y3 ET7 s&2 O19D7T6^l ^Ac '8 $7$k $i $nc ^0 ^2i72 i77o11^0 ^1 ^1s0v$e $3$3 $5 $0-2-5s45 

Any suggestions on how I can work around this?

**Comment by Shooter3k** [comment]
looks like to fix it you replace the write! macros with writeln! in src/duprule.rs

**Comment by n0kovo** [comment]
I made a PR for this
https://github.com/0xbsec/duprule/pull/33

**Comment by mhasbini** [comment]
Fixed in #33. Thanks!
